# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Cal.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CAL(object):
    def setupUi(self, CAL):
        CAL.setObjectName("CAL")
        CAL.resize(370, 530)
        CAL.setMinimumSize(QtCore.QSize(370, 530))
        CAL.setMaximumSize(QtCore.QSize(370, 530))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        CAL.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CAL.setWindowIcon(icon)
        CAL.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(CAL)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 250, 82, 62))
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_7.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 320, 82, 62))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_4.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 390, 82, 62))
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_1.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(10, 460, 174, 62))
        self.pushButton_0.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_0.setIconSize(QtCore.QSize(174, 62))
        self.pushButton_0.setFlat(False)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 390, 82, 62))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 320, 82, 62))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 250, 82, 62))
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_8.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 250, 82, 62))
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_9.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 320, 82, 62))
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 390, 82, 62))
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_point = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_point.setGeometry(QtCore.QRect(190, 460, 82, 62))
        self.pushButton_point.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_point.setFont(font)
        self.pushButton_point.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_point.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_point.setFlat(False)
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(280, 320, 82, 62))
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_add.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_add.setFlat(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_min = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_min.setGeometry(QtCore.QRect(280, 250, 82, 62))
        self.pushButton_min.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_min.setFont(font)
        self.pushButton_min.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_min.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_min.setFlat(False)
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_mul = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mul.setGeometry(QtCore.QRect(280, 180, 82, 62))
        self.pushButton_mul.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_mul.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_mul.setFlat(False)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_div = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_div.setGeometry(QtCore.QRect(280, 110, 82, 62))
        self.pushButton_div.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_div.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_div.setFlat(False)
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_lbr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lbr.setGeometry(QtCore.QRect(10, 180, 131, 62))
        self.pushButton_lbr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_lbr.setFont(font)
        self.pushButton_lbr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_lbr.setIconSize(QtCore.QSize(131, 62))
        self.pushButton_lbr.setFlat(False)
        self.pushButton_lbr.setObjectName("pushButton_lbr")
        self.pushButton_rbr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rbr.setGeometry(QtCore.QRect(150, 180, 121, 62))
        self.pushButton_rbr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_rbr.setFont(font)
        self.pushButton_rbr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_rbr.setIconSize(QtCore.QSize(131, 62))
        self.pushButton_rbr.setFlat(False)
        self.pushButton_rbr.setObjectName("pushButton_rbr")
        self.pushButton_c = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_c.setGeometry(QtCore.QRect(10, 110, 171, 62))
        self.pushButton_c.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_c.setFont(font)
        self.pushButton_c.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_c.setIconSize(QtCore.QSize(171, 62))
        self.pushButton_c.setFlat(False)
        self.pushButton_c.setObjectName("pushButton_c")
        self.pushButton_equ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equ.setGeometry(QtCore.QRect(280, 390, 82, 131))
        self.pushButton_equ.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equ.setFont(font)
        self.pushButton_equ.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_equ.setIconSize(QtCore.QSize(82, 131))
        self.pushButton_equ.setFlat(False)
        self.pushButton_equ.setObjectName("pushButton_equ")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(190, 110, 82, 62))
        self.pushButton_back.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_back.setIconSize(QtCore.QSize(82, 62))
        self.pushButton_back.setFlat(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-width:0;border-style:outset;background-color:rgb(240, 240, 240)")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("border-width:0;border-style:outset;background-color:rgb(240, 240, 240)")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit.raise_()
        self.pushButton_7.raise_()
        self.pushButton_4.raise_()
        self.pushButton_1.raise_()
        self.pushButton_0.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_6.raise_()
        self.pushButton_3.raise_()
        self.pushButton_point.raise_()
        self.pushButton_add.raise_()
        self.pushButton_min.raise_()
        self.pushButton_mul.raise_()
        self.pushButton_div.raise_()
        self.pushButton_lbr.raise_()
        self.pushButton_rbr.raise_()
        self.pushButton_c.raise_()
        self.pushButton_equ.raise_()
        self.pushButton_back.raise_()
        self.lineEdit_2.raise_()
        CAL.setCentralWidget(self.centralwidget)

        self.retranslateUi(CAL)
        QtCore.QMetaObject.connectSlotsByName(CAL)

    def retranslateUi(self, CAL):
        _translate = QtCore.QCoreApplication.translate
        CAL.setWindowTitle(_translate("CAL", "计算器"))
        self.pushButton_7.setText(_translate("CAL", "7"))
        self.pushButton_4.setText(_translate("CAL", "4"))
        self.pushButton_1.setText(_translate("CAL", "1"))
        self.pushButton_0.setText(_translate("CAL", "0"))
        self.pushButton_2.setText(_translate("CAL", "2"))
        self.pushButton_5.setText(_translate("CAL", "5"))
        self.pushButton_8.setText(_translate("CAL", "8"))
        self.pushButton_9.setText(_translate("CAL", "9"))
        self.pushButton_6.setText(_translate("CAL", "6"))
        self.pushButton_3.setText(_translate("CAL", "3"))
        self.pushButton_point.setText(_translate("CAL", "."))
        self.pushButton_add.setText(_translate("CAL", "+"))
        self.pushButton_min.setText(_translate("CAL", "-"))
        self.pushButton_mul.setText(_translate("CAL", "×"))
        self.pushButton_div.setText(_translate("CAL", "÷"))
        self.pushButton_lbr.setText(_translate("CAL", "("))
        self.pushButton_rbr.setText(_translate("CAL", ")"))
        self.pushButton_c.setText(_translate("CAL", "C"))
        self.pushButton_equ.setText(_translate("CAL", "="))
        self.pushButton_back.setText(_translate("CAL", "←"))
